image:
  - Visual Studio 2022
  - macOS
  - Ubuntu

skip_branch_with_pr: true
stack: python 3.11

environment:
  GITHUB_TOKEN:
    secure: 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

install:
  - pip install -r requirements.txt

build_script:
  - flet pack src/client/main.py --name EasyViewer --icon icon/icon.png --product-name EasyViewer --product-version "1.0.0" --copyright "Copyright (c) 2023 Raul Catalinas Esteban"

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
#
for:
  - matrix:
      only:
        - image: Visual Studio 2022

    after_build:
      - 7z a EasyViewer-windows.zip %CD%\dist\*.exe

    artifacts:
      - path: EasyViewer-windows.zip

  #
  #   macOS package
  #
  - matrix:
      only:
        - image: macOS

    after_build:
      - tar -czvf EasyViewer-macos.tar.gz -C dist counter.app

    artifacts:
      - path: EasyViewer-macos.tar.gz

  #
  #   Linux package
  #
  - matrix:
      only:
        - image: Ubuntu

    after_build:
      - tar -czvf EasyViewer-linux.tar.gz -C dist counter

    artifacts:
      - path: EasyViewer-linux.tar.gz
