from enum import StrEnum


class ExcelTextLoaderKeys(StrEnum):
    SELECT_LOCATION = "select_location"
    DOWNLOAD_VIDEO = "download_video"
    DOWNLOAD_AUDIO = "download_audio"
    EXIT_CONFIRMATION_BODY = "exit_confirmation_body"
    YES_OPTION = "yes_option"
    CONTACT = "contact"
    CHANGE_LANGUAGE = "change_language"
    SPANISH_LANGUAGE = "spanish_language"
    ENGLISH_LANGUAGE = "english_language"
    ERROR_EMPTY_URL = "error_empty_url"
    ERROR_CONNECTION = "error_connection"
    ERROR_YOUTUBE_URL = "error_youtube_url"
    EXIT_CONFIRMATION_TITLE = "exit_confirmation_title"
    SELECT_DIRECTORY = "select_directory"
    PLACEHOLDER_URL = "placeholder_url"
    PLACEHOLDER_DIRECTORY = "placeholder_directory"
    SOCIAL_MEDIA = "social_media"
    UPDATE_AVAILABLE_TITLE = "update available_title"
    UPDATE_AVAILABLE_BODY = "update available_body"
    LATER_OPTION = "later_option"
    CHECK_UPDATES = "check_updates"
    UPDATED_VERSION_TITLE = "updated_version_title"
    UPDATED_VERSION_BODY = "updated_version_body"
    ERROR_AGE_RESTRICTED = "error_age_restricted"
    ERROR_LIVE_STREAM = "error_live_stream"
    ERROR_ONLY_MEMBERS = "error_only_members"
    ERROR_PRIVATE_VIDEO = "error_private_video"
    ERROR_BLOCKED_REGION = "error_blocked_region"
    ERROR_DEFAULT = "error_default"
    WHATS_NEW_TITLE = "whats_new_title"
    LIABILITY_NOTICE_TITLE = "liability_notice_title"
    LIABILITY_NOTICE_BODY = "liability_notice_body"
